x-airflow-common: 
  &airflow-common
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    AIRFLOW__CORE__LOAD_EXAMPLES: False
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./libraries:/opt/airflow/libraries
    - ./output_files:/opt/airflow/output_files
    - ./airflow.db:/opt/airflow/airflow.db
    - ./certs:/opt/airflow/certs
    - ./config:/opt/airflow/config

services:
  airflow:
    <<: *airflow-common
    image: my_custom_airflow_image
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init && airflow users create --username ${AIRFLOW_USER_USERNAME} --password ${AIRFLOW_USER_PASSWORD} --firstname ${AIRFLOW_USER_FIRSTNAME} --lastname ${AIRFLOW_USER_LASTNAME} --role Admin --email ${AIRFLOW_USER_EMAIL} &&
      airflow webserver
      "
    restart: always

  airflow_scheduler:
    <<: *airflow-common
    image: my_custom_airflow_image
    command: >
      bash -c "
      airflow scheduler
      "
    restart: always